kind: pipeline
type: kubernetes
name: staging

trigger:
  branch:
    - staging

steps:
  # Build and publish frontend Docker image
  - name: publish-frontend
    image: plugins/kaniko-ecr
    settings:
      dockerfile: Dockerfile.frontend
      create_repository: true
      registry: 795250896452.dkr.ecr.us-east-1.amazonaws.com
      repo: industrysolutions/fsi-payments-frontend
      tags:
        - git-${DRONE_COMMIT_SHA:0:7}
        - latest
      access_key:
        from_secret: ecr_access_key
      secret_key:
        from_secret: ecr_secret_key
    when:
      event:
        - push

  # Deploy frontend to staging
  - name: deploy-frontend-staging
    image: public.ecr.aws/kanopy/drone-helm:v3
    settings:
      chart: mongodb/web-app
      chart_version: 4.25.0
      add_repos: [mongodb=https://10gen.github.io/helm-charts]
      namespace: industrysolutions
      release: fsi-payments-frontend
      values_files: ["environment/staging.yaml"]
      values:
        - "image.tag=git-${DRONE_COMMIT_SHA:0:7}"
        - "image.repository=795250896452.dkr.ecr.us-east-1.amazonaws.com/industrysolutions/fsi-payments-frontend"
        - "ingress.enabled=true"
        - "mesh.enabled=true"
        - "ingress.hosts[0]=fsi-payments-frontend.industrysolutions.staging.corp.mongodb.com"
        - "resources.limits.cpu=1000m"
        - "resources.limits.memory=1024Mi"
        - "resources.requests.cpu=250m"
        - "resources.requests.memory=256Mi"
      api_server: https://api.staging.corp.mongodb.com
      kubernetes_token:
        from_secret: staging_kubernetes_token
    when:
      event:
        - push
      branch:
        - staging

# ---
# kind: pipeline
# type: kubernetes
# name: fsi-payments-backend

# platform:
#   arch: arm64  # Change to 'amd64' if needed

# trigger:
#   branch:
#     - main
#     - staging
#   event:
#     - push
#     - pull_request

# steps:
#   # Build and publish backend Docker image
#   - name: publish-backend
#     image: plugins/kaniko-ecr
#     settings:
#       dockerfile: Dockerfile.backend
#       create_repository: true
#       registry: 795250896452.dkr.ecr.us-east-1.amazonaws.com
#       repo: industrysolutions/${DRONE_REPO_NAME}-backend
#       tags:
#         - git-${DRONE_COMMIT_SHA:0:7}
#         - latest
#         - ${DRONE_BRANCH}
#       access_key:
#         from_secret: ecr_access_key
#       secret_key:
#         from_secret: ecr_secret_key
#     when:
#       event:
#         - push
#       branch:
#         - main
#         - staging

#   # Deploy backend to staging
#   - name: deploy-backend-staging
#     image: public.ecr.aws/kanopy/drone-helm:v3
#     settings:
#       chart: mongodb/web-app
#       chart_version: 4.25.0
#       add_repos: [mongodb=https://10gen.github.io/helm-charts]
#       namespace: industrysolutions
#       release: fsi-payments-backend
#       values_files: ["environment/staging-backend.yaml"]
#       values: >
#         image.tag=git-${DRONE_COMMIT_SHA:0:7},
#         image.repository=795250896452.dkr.ecr.us-east-1.amazonaws.com/industrysolutions/${DRONE_REPO_NAME}-backend,
#         ingress.enabled=true,
#         ingress.hosts[0]=fsi-payments-backend.industrysolutions.staging.corp.mongodb.com,
#         service.port=8080,
#         containerPort=8080,
#         livenessProbe.httpGet.path=/api/v1/converter/health,
#         livenessProbe.httpGet.port=8080,
#         readinessProbe.httpGet.path=/api/v1/converter/health,
#         readinessProbe.httpGet.port=8080
#       api_server: https://api.staging.corp.mongodb.com
#       kubernetes_token:
#         from_secret: staging_kubernetes_token
#     when:
#       event:
#         - push
#       branch:
#         - staging