FROM node:22-bookworm-slim
WORKDIR /app

COPY frontend/package*.json ./

RUN npm install --legacy-peer-deps
RUN npm install -D @playwright/test --legacy-peer-deps
RUN npx playwright install-deps chromium
RUN npx playwright install --with-deps chromium

# Copy all frontend files INCLUDING configs
COPY frontend/ ./


ARG BIAN_MODEL_URL=https://leafy-bank-bian-model.industrysolutions.staging.corp.mongodb.com
ENV BIAN_MODEL_URL=$BIAN_MODEL_URL

# Build the application
RUN npm run build
ENV APP_NAME=agentic-payments
ENV ENV_NAME=staging


CMD ["npx", "playwright", "test", "/tests", "--reporter=json", ">", "results.json"]
